- name: Add tmux config
  become: huw
  ansible.builtin.shell: |
    git clone https://github.com/HFulcher/.dotfiles
    ln -s ./.dotfiles/tmux/.tmux.conf ./.tmux.conf
    ln -s ./.dotfiles/i3 ./.config/i3
    ln -s ./.dotfiles/kitty ./.config/kitty

    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  args:
    chdir: "/home/{{ username }}/"
    executable: /bin/bash
